name: R-CMD-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::devtools
            any::rcmdcheck
          extra-packages: metafor

      - name: Install LaTeX
        run: |
          if [[ "$(uname)" == "Linux" ]]; then
            sudo apt-get install -y texlive-latex-base
          elif [[ "$(uname)" == "Darwin" ]]; then
            brew install --cask mactex
          fi

      - name: Install TinyTeX
        run: |
          Rscript -e 'install.packages("tinytex")'
          Rscript -e 'tinytex::install_tinytex()'

      - name: Run tests
        run: |
          rcmdcheck::rcmdcheck(error_on = "warning")
        shell: Rscript {0}
